version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-url-shortener
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - default

  url-shortener:
    image: marcusferreira04/url-shortener
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
       - MYSQL_URL=jdbc:mysql://mysql-url-shortener:3306/URL_DB?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
       - MYSQL_USER=root
       - MYSQL_PASSWORD=1234
    networks:
      - default
    depends_on:
      - mysql-db

networks:
  default:
    driver: bridge
